# Site settings
title: Paul Schwartzberg
description: Paul Schwartzberg's portfolio — Senior Software Developer | Azure | .NET | Angular with 20+ years experience.
url: "https://schwartzberg.github.io"

# User settings
username: Paul Schwartzberg
email: schwartzenberg@gmail.com

# Global settings
icon_size: 58

exclude: [vendor]

# Google Analytics tracking ID
google_analytics_tracking_id: